package polyschema

import (
	"flag"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"testing/fstest"
)

var update = flag.Bool("update", false, "rewrite golden files")

type want struct {
	sql   string // statements joined by ";\n"
	issue string // substring of the joined Issue.String()s; "" = expect none
}

// expect renders one operation (outside a transaction, so MySQL's implicit
// commit warning stays out of the way) for each dialect. MariaDB defaults to
// the MySQL expectation, SQLite to the Postgres one.
func expect(t *testing.T, op string, cases map[*Dialect]want) {
	t.Helper()
	f, err := Parse("1_t.yml", []byte("transaction: false\noperations:\n  - "+op))
	if err != nil {
		t.Fatalf("%s: %v", op, err)
	}
	for _, d := range All {
		w, ok := cases[d]
		switch {
		case !ok && d == MariaDB:
			w = cases[MySQL]
		case !ok && d == SQLite:
			w = cases[Postgres]
		}
		stmts, issues := Render(f, d)
		var sqls, is []string
		for _, s := range stmts {
			sqls = append(sqls, s.SQL)
		}
		for _, i := range issues {
			is = append(is, i.String())
		}
		if got := strings.Join(sqls, ";\n"); got != w.sql {
			t.Errorf("%s\n[%s] sql:\n got: %s\nwant: %s", op, d, got, w.sql)
		}
		all := strings.Join(is, "\n")
		if (w.issue == "") != (len(is) == 0) || !strings.Contains(all, w.issue) {
			t.Errorf("%s\n[%s] issues:\n got: %s\nwant: %q", op, d, all, w.issue)
		}
	}
}

// bt converts Postgres-style quoting to MySQL backticks, for readability.
func bt(s string) string { return strings.ReplaceAll(s, `"`, "`") }

func TestTables(t *testing.T) {
	expect(t, "dropTable: {name: t, ifExists: true, cascade: true}", map[*Dialect]want{
		Postgres: {`DROP TABLE IF EXISTS "t" CASCADE`, ""},
		MySQL:    {"DROP TABLE IF EXISTS `t`", "1_t.yml:1 mysql warning: mysql ignores cascade"},
		MariaDB:  {"DROP TABLE IF EXISTS `t`", "mariadb warning: mariadb ignores cascade"},
		SQLite:   {`DROP TABLE IF EXISTS "t"`, "sqlite warning: sqlite ignores cascade"},
	})
	expect(t, "dropTable: {name: t}", map[*Dialect]want{
		Postgres: {`DROP TABLE "t"`, ""},
		MySQL:    {"DROP TABLE `t`", ""},
	})
	expect(t, "renameTable: {from: a, to: b}", map[*Dialect]want{
		Postgres: {`ALTER TABLE "a" RENAME TO "b"`, ""},
		MySQL:    {bt(`ALTER TABLE "a" RENAME TO "b"`), ""},
	})
}

func TestCreateTable(t *testing.T) {
	mysql := bt(`CREATE TABLE IF NOT EXISTS "t" (
  "id" BIGINT NOT NULL AUTO_INCREMENT,
  "ok" TINYINT(1) DEFAULT 0,
  "at" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "n" INTEGER DEFAULT (1 + 1),
  PRIMARY KEY ("id"),
  UNIQUE INDEX "i" ("ok")
)`)
	expect(t, `createTable:
      name: t
      ifNotExists: true
      columns:
        - {name: id, type: bigint, primaryKey: true, autoIncrement: true}
        - {name: ok, type: boolean, default: false}
        - {name: at, type: timestamptz, defaultExpr: current_timestamp}
        - {name: n, type: integer, defaultExpr: "1 + 1"}
      indexes: [{name: i, columns: [ok], unique: true}]`, map[*Dialect]want{
		Postgres: {`CREATE TABLE IF NOT EXISTS "t" (
  "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "ok" BOOLEAN DEFAULT FALSE,
  "at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "n" INTEGER DEFAULT (1 + 1),
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "i" ON "t" ("ok")`, ""},
		MySQL:   {mysql, "mysql warning: mysql has no time-zone-aware timestamp"},
		MariaDB: {mysql, "mariadb warning: mariadb has no time-zone-aware timestamp"},
		SQLite: {`CREATE TABLE IF NOT EXISTS "t" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "ok" INTEGER DEFAULT 0,
  "at" TEXT DEFAULT CURRENT_TIMESTAMP,
  "n" INTEGER DEFAULT (1 + 1)
);
CREATE UNIQUE INDEX IF NOT EXISTS "i" ON "t" ("ok")`, ""},
	})

	// Composite key, uniques, FKs, checks and a partial index.
	mysql = bt(`CREATE TABLE "t" (
  "a" INTEGER NOT NULL,
  "b" VARCHAR(5) NOT NULL UNIQUE,
  "j" JSON DEFAULT '{}',
  PRIMARY KEY ("a", "b"),
  CONSTRAINT "u" UNIQUE ("a"),
  INDEX "i" ("b"),
  CONSTRAINT "f" FOREIGN KEY ("a") REFERENCES "r" ("id") ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT "c" CHECK (a > 0)
)`)
	expect(t, `createTable:
      name: t
      primaryKey: [a, b]
      columns: [{name: a, type: integer}, {name: b, type: string, length: 5, unique: true}, {name: j, type: json, default: "{}"}]
      uniques: [{name: u, columns: [a]}]
      foreignKeys: [{name: f, columns: [a], refTable: r, refColumns: [id], onDelete: cascade, onUpdate: restrict}]
      checks: [{name: c, expr: "a > 0"}]
      indexes: [{name: i, columns: [b], where: "a > 1"}]`, map[*Dialect]want{
		Postgres: {`CREATE TABLE "t" (
  "a" INTEGER NOT NULL,
  "b" VARCHAR(5) NOT NULL UNIQUE,
  "j" JSONB DEFAULT '{}',
  PRIMARY KEY ("a", "b"),
  CONSTRAINT "u" UNIQUE ("a"),
  CONSTRAINT "f" FOREIGN KEY ("a") REFERENCES "r" ("id") ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT "c" CHECK (a > 0)
);
CREATE INDEX "i" ON "t" ("b") WHERE a > 1`, ""},
		MySQL:   {mysql, "error: MySQL doesn't allow a literal default on json column j"},
		MariaDB: {mysql, "error: mariadb has no partial indexes"},
		SQLite: {`CREATE TABLE "t" (
  "a" INTEGER NOT NULL,
  "b" TEXT NOT NULL UNIQUE,
  "j" TEXT DEFAULT '{}',
  PRIMARY KEY ("a", "b"),
  CONSTRAINT "u" UNIQUE ("a"),
  CONSTRAINT "f" FOREIGN KEY ("a") REFERENCES "r" ("id") ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT "c" CHECK (a > 0)
);
CREATE INDEX "i" ON "t" ("b") WHERE a > 1`, ""},
	})
}

func TestTypes(t *testing.T) {
	cols := make([]string, 0, len(typeNames))
	for _, ty := range typeList() {
		extra := ""
		if ty == "decimal" {
			extra = ", precision: 8, scale: 2"
		}
		cols = append(cols, "{name: c_"+ty+", type: "+ty+extra+"}")
	}
	f := ops(t, "  - createTable: {name: t, columns: ["+strings.Join(cols, ", ")+"]}\n")
	got := map[string][]string{}
	for _, d := range []*Dialect{Postgres, MySQL, SQLite} {
		for _, c := range f.Operations[0].CreateTable.Columns {
			got[d.name] = append(got[d.name], d.columnType(&c))
		}
	}
	wantTypes := map[string][]string{
		"postgres": {"BIGINT", "BYTEA", "BOOLEAN", "DATE", "NUMERIC(8,2)", "DOUBLE PRECISION", "REAL", "INTEGER", "JSONB", "SMALLINT", "VARCHAR(255)", "TEXT", "TIME", "TIMESTAMP", "TIMESTAMPTZ", "UUID"},
		"mysql":    {"BIGINT", "BLOB", "TINYINT(1)", "DATE", "DECIMAL(8,2)", "DOUBLE", "FLOAT", "INTEGER", "JSON", "SMALLINT", "VARCHAR(255)", "TEXT", "TIME", "DATETIME", "DATETIME", "CHAR(36)"},
		"sqlite":   {"INTEGER", "BLOB", "INTEGER", "TEXT", "NUMERIC", "REAL", "REAL", "INTEGER", "TEXT", "INTEGER", "TEXT", "TEXT", "TEXT", "TEXT", "TEXT", "TEXT"},
	}
	if !reflect.DeepEqual(got, wantTypes) {
		t.Errorf("types (in %v order):\n got %v\nwant %v", typeList(), got, wantTypes)
	}
}

func TestColumns(t *testing.T) {
	expect(t, `addColumn: {table: t, column: {name: c, type: string, length: 10, nullable: false, default: "it's \\ok"}}`, map[*Dialect]want{
		Postgres: {`ALTER TABLE "t" ADD COLUMN "c" VARCHAR(10) NOT NULL DEFAULT 'it''s \ok'`, ""},
		MySQL:    {`ALTER TABLE ` + "`t`" + ` ADD COLUMN ` + "`c`" + ` VARCHAR(10) NOT NULL DEFAULT 'it''s \\ok'`, ""},
		SQLite:   {`ALTER TABLE "t" ADD COLUMN "c" TEXT NOT NULL DEFAULT 'it''s \ok'`, ""},
	})
	expect(t, "addColumn: {table: t, ifNotExists: true, column: {name: c, type: integer, default: 1.5}}", map[*Dialect]want{
		Postgres: {`ALTER TABLE "t" ADD COLUMN IF NOT EXISTS "c" INTEGER DEFAULT 1.5`, ""},
		MySQL:    {bt(`ALTER TABLE "t" ADD COLUMN IF NOT EXISTS "c" INTEGER DEFAULT 1.5`), "error: mysql doesn't support ADD COLUMN IF NOT EXISTS"},
		MariaDB:  {bt(`ALTER TABLE "t" ADD COLUMN IF NOT EXISTS "c" INTEGER DEFAULT 1.5`), ""},
		SQLite:   {`ALTER TABLE "t" ADD COLUMN IF NOT EXISTS "c" INTEGER DEFAULT 1.5`, "error: sqlite doesn't support ADD COLUMN IF NOT EXISTS"},
	})
	for op, issue := range map[string]string{
		"addColumn: {table: t, column: {name: c, type: text, unique: true}}":                   "can't add a UNIQUE column",
		"addColumn: {table: t, column: {name: c, type: text, defaultExpr: CURRENT_TIMESTAMP}}": "expression default",
		"addColumn: {table: t, column: {name: c, type: text, nullable: false}}":                "NOT NULL column without a default",
	} {
		f := ops(t, "  - "+op+"\n")
		if _, is := Render(f, SQLite); len(is) != 1 || !strings.Contains(is[0].Message, issue) {
			t.Errorf("%s: sqlite issues %v, want %q", op, is, issue)
		}
		if _, is := Render(f, Postgres); len(is) != 0 {
			t.Errorf("%s: postgres issues %v", op, is)
		}
	}
	expect(t, "dropColumn: {table: t, name: c, ifExists: true}", map[*Dialect]want{
		Postgres: {`ALTER TABLE "t" DROP COLUMN IF EXISTS "c"`, ""},
		MySQL:    {bt(`ALTER TABLE "t" DROP COLUMN IF EXISTS "c"`), "error: mysql doesn't support DROP COLUMN IF EXISTS"},
		MariaDB:  {bt(`ALTER TABLE "t" DROP COLUMN IF EXISTS "c"`), ""},
		SQLite:   {`ALTER TABLE "t" DROP COLUMN IF EXISTS "c"`, "error: sqlite doesn't support DROP COLUMN IF EXISTS"},
	})
	expect(t, "renameColumn: {table: t, from: a, to: b}", map[*Dialect]want{
		Postgres: {`ALTER TABLE "t" RENAME COLUMN "a" TO "b"`, ""},
		MySQL:    {bt(`ALTER TABLE "t" RENAME COLUMN "a" TO "b"`), ""},
	})
	expect(t, `alterColumn: {table: t, name: c, type: string, length: 100, nullable: false, default: ""}`, map[*Dialect]want{
		Postgres: {`ALTER TABLE "t" ALTER COLUMN "c" TYPE VARCHAR(100), ALTER COLUMN "c" SET NOT NULL, ALTER COLUMN "c" SET DEFAULT ''`, ""},
		MySQL:    {bt(`ALTER TABLE "t" MODIFY COLUMN "c" VARCHAR(100) NOT NULL DEFAULT ''`), ""},
		SQLite:   {"", "error: SQLite can't alter a column in an existing table"},
	})
	expect(t, "alterColumn: {table: t, name: c, type: integer}", map[*Dialect]want{
		Postgres: {`ALTER TABLE "t" ALTER COLUMN "c" TYPE INTEGER, ALTER COLUMN "c" DROP NOT NULL, ALTER COLUMN "c" DROP DEFAULT`, ""},
		MySQL:    {bt(`ALTER TABLE "t" MODIFY COLUMN "c" INTEGER`), ""},
		SQLite:   {"", "table rebuild"},
	})
}

func TestIndexesAndConstraints(t *testing.T) {
	expect(t, "createIndex: {table: t, name: i, columns: [a, b], unique: true, ifNotExists: true, where: active}", map[*Dialect]want{
		Postgres: {`CREATE UNIQUE INDEX IF NOT EXISTS "i" ON "t" ("a", "b") WHERE active`, ""},
		MySQL:    {bt(`CREATE UNIQUE INDEX IF NOT EXISTS "i" ON "t" ("a", "b") WHERE active`), "error: MySQL doesn't support CREATE INDEX IF NOT EXISTS"},
		MariaDB:  {bt(`CREATE UNIQUE INDEX IF NOT EXISTS "i" ON "t" ("a", "b") WHERE active`), "error: mariadb has no partial indexes"},
	})
	expect(t, "createIndex: {table: t, name: i, columns: [a]}", map[*Dialect]want{
		Postgres: {`CREATE INDEX "i" ON "t" ("a")`, ""},
		MySQL:    {bt(`CREATE INDEX "i" ON "t" ("a")`), ""},
	})
	expect(t, "dropIndex: {table: t, name: i, ifExists: true}", map[*Dialect]want{
		Postgres: {`DROP INDEX IF EXISTS "i"`, ""},
		MySQL:    {bt(`DROP INDEX IF EXISTS "i" ON "t"`), "error: mysql doesn't support DROP INDEX IF EXISTS"},
		MariaDB:  {bt(`DROP INDEX IF EXISTS "i" ON "t"`), ""},
	})
	expect(t, "addUnique: {table: t, name: u, columns: [a]}", map[*Dialect]want{
		Postgres: {`ALTER TABLE "t" ADD CONSTRAINT "u" UNIQUE ("a")`, ""},
		MySQL:    {bt(`ALTER TABLE "t" ADD CONSTRAINT "u" UNIQUE ("a")`), ""},
		SQLite:   {`CREATE UNIQUE INDEX "u" ON "t" ("a")`, "warning: SQLite can't add constraints"},
	})
	expect(t, "dropUnique: {table: t, name: u}", map[*Dialect]want{
		Postgres: {`ALTER TABLE "t" DROP CONSTRAINT "u"`, ""},
		MySQL:    {bt(`ALTER TABLE "t" DROP INDEX "u"`), ""},
		SQLite:   {`DROP INDEX "u"`, "warning: SQLite can't drop constraints"},
	})
	expect(t, "addForeignKey: {table: t, name: f, columns: [a], refTable: r, refColumns: [id], onDelete: set null, onUpdate: No Action}", map[*Dialect]want{
		Postgres: {`ALTER TABLE "t" ADD CONSTRAINT "f" FOREIGN KEY ("a") REFERENCES "r" ("id") ON DELETE SET NULL ON UPDATE NO ACTION`, ""},
		MySQL:    {bt(`ALTER TABLE "t" ADD CONSTRAINT "f" FOREIGN KEY ("a") REFERENCES "r" ("id") ON DELETE SET NULL ON UPDATE NO ACTION`), ""},
		SQLite:   {"", "error: SQLite can't add a foreign key to"},
	})
	expect(t, "dropForeignKey: {table: t, name: f}", map[*Dialect]want{
		Postgres: {`ALTER TABLE "t" DROP CONSTRAINT "f"`, ""},
		MySQL:    {bt(`ALTER TABLE "t" DROP FOREIGN KEY "f"`), ""},
		SQLite:   {"", "error: SQLite can't drop a foreign key from"},
	})
	expect(t, "addCheck: {table: t, name: c, expr: a > 0}", map[*Dialect]want{
		Postgres: {`ALTER TABLE "t" ADD CONSTRAINT "c" CHECK (a > 0)`, ""},
		MySQL:    {bt(`ALTER TABLE "t" ADD CONSTRAINT "c" CHECK (a > 0)`), ""},
		SQLite:   {"", "error: SQLite can't add a check constraint to"},
	})
	expect(t, "dropCheck: {table: t, name: c}", map[*Dialect]want{
		Postgres: {`ALTER TABLE "t" DROP CONSTRAINT "c"`, ""},
		MySQL:    {bt(`ALTER TABLE "t" DROP CHECK "c"`), ""},
		MariaDB:  {bt(`ALTER TABLE "t" DROP CONSTRAINT "c"`), ""},
		SQLite:   {"", "error: SQLite can't drop a check constraint from"},
	})
}

func TestData(t *testing.T) {
	f := ops(t, `  - insert: {table: t, rows: [{b: 2, a: x}, {c: null, j: {k: [1, 2]}}]}
  - update: {table: t, set: {b: 3, a: y}, where: {c: null, d: true, e: 5}}
  - update: {table: t, set: {a: z}, all: true}
  - delete: {table: t, where: {a: x}}
  - delete: {table: t, all: true}
`)
	for d, wantSQL := range map[*Dialect][]string{
		Postgres: {
			`INSERT INTO "t" ("a", "b") VALUES ($1, $2)`,
			`INSERT INTO "t" ("c", "j") VALUES ($1, $2)`,
			`UPDATE "t" SET "a" = $1, "b" = $2 WHERE "c" IS NULL AND "d" = $3 AND "e" = $4`,
			`UPDATE "t" SET "a" = $1`,
			`DELETE FROM "t" WHERE "a" = $1`,
			`DELETE FROM "t"`,
		},
		MySQL: {
			"INSERT INTO `t` (`a`, `b`) VALUES (?, ?)",
			"INSERT INTO `t` (`c`, `j`) VALUES (?, ?)",
			"UPDATE `t` SET `a` = ?, `b` = ? WHERE `c` IS NULL AND `d` = ? AND `e` = ?",
			"UPDATE `t` SET `a` = ?",
			"DELETE FROM `t` WHERE `a` = ?",
			"DELETE FROM `t`",
		},
	} {
		stmts, issues := Render(f, d)
		if len(issues) != 0 {
			t.Errorf("%s: issues %v", d, issues)
		}
		var got []string
		for _, s := range stmts {
			got = append(got, s.SQL)
		}
		if !reflect.DeepEqual(got, wantSQL) {
			t.Errorf("%s:\n got %q\nwant %q", d, got, wantSQL)
		}
		wantArgs := [][]any{{"x", 2}, {nil, `{"k":[1,2]}`}, {"y", 3, true, 5}, {"z"}, {"x"}, nil}
		for i, s := range stmts {
			if !reflect.DeepEqual(s.Args, wantArgs[i]) {
				t.Errorf("%s stmt %d args = %#v, want %#v", d, i, s.Args, wantArgs[i])
			}
			if wantOp := []int{1, 1, 2, 3, 4, 5}[i]; s.Op != wantOp {
				t.Errorf("%s stmt %d op = %d", d, i, s.Op)
			}
		}
	}

	// Values that can't become JSON are reported, not silently dropped.
	g := &gen{d: Postgres}
	if g.arg([]any{func() {}}) != nil || len(g.issues) != 1 {
		t.Errorf("unmarshalable value: issues %v", g.issues)
	}
}

func TestRawSQL(t *testing.T) {
	expect(t, "sql: {postgres: P, mysql: M, default: D}", map[*Dialect]want{
		Postgres: {"P", ""}, MySQL: {"M", ""}, MariaDB: {"M", ""}, SQLite: {"D", ""},
	})
	expect(t, "sql: {mariadb: MA, sqlite: S}", map[*Dialect]want{
		Postgres: {"", "error: sql has no entry for postgres and no default"},
		MySQL:    {"", "error: sql has no entry for mysql"},
		MariaDB:  {"MA", ""},
		SQLite:   {"S", ""},
	})
}

func TestQuoting(t *testing.T) {
	if got := Postgres.q(`we"ird`); got != `"we""ird"` {
		t.Errorf("postgres quote = %s", got)
	}
	if got := MySQL.q("we`ird"); got != "`we``ird`" {
		t.Errorf("mysql quote = %s", got)
	}
	if MySQL.literal(true) != "1" || Postgres.literal(true) != "TRUE" || SQLite.literal(nil) != "NULL" || Postgres.literal(uint64(7)) != "7" {
		t.Error("literal rendering")
	}
}

func TestMySQLTransactionWarning(t *testing.T) {
	ddl := "operations: [{dropTable: {name: t}}]"
	for _, tc := range []struct {
		data string
		warn bool
	}{
		{ddl, true},
		{"transaction: false\n" + ddl, false},
		{"operations: [{delete: {table: t, all: true}}]", false},
	} {
		f, err := Parse("1_t.yml", []byte(tc.data))
		if err != nil {
			t.Fatal(err)
		}
		_, issues := Render(f, MySQL)
		if got := len(issues) == 1 && issues[0].Op == 0; got != tc.warn {
			t.Errorf("%q: issues %v, want warning=%v", tc.data, issues, tc.warn)
		}
		if _, issues := Render(f, Postgres); len(issues) != 0 {
			t.Errorf("postgres issues %v", issues)
		}
	}
}

func TestCheckAndMisc(t *testing.T) {
	fsys := fstest.MapFS{"1_a.yml": {Data: []byte("operations: [{alterColumn: {table: t, name: c, type: text}}]")}}
	issues, err := CheckFS(fsys, All...)
	if err != nil {
		t.Fatal(err)
	}
	// MySQL + MariaDB transaction warnings, SQLite rebuild error.
	if len(issues) != 3 || issues[2].Severity != Error || issues[2].Engine != "sqlite" {
		t.Errorf("issues = %v", issues)
	}
	if _, err := CheckFS(fstest.MapFS{"1_a.yml": {Data: []byte("bad")}}); err == nil {
		t.Error("CheckFS should surface load errors")
	}
	if Warning.String() != "warning" || Error.String() != "error" {
		t.Error("severity strings")
	}
	if DialectByName("MariaDB") != MariaDB || DialectByName("oracle") != nil || SQLite.String() != "sqlite" {
		t.Error("DialectByName")
	}
}

// TestGolden renders testdata/migrations for every engine and compares with
// testdata/golden/<engine>/<file>.sql. Run with -update to rewrite them.
func TestGolden(t *testing.T) {
	files, err := Load(os.DirFS("testdata/migrations"))
	if err != nil {
		t.Fatal(err)
	}
	for _, d := range All {
		for _, f := range files {
			stmts, issues := Render(f, d)
			var b strings.Builder
			for _, is := range issues {
				b.WriteString("-- " + is.String() + "\n")
			}
			for _, s := range stmts {
				b.WriteString(s.SQL + ";\n")
			}
			path := filepath.Join("testdata", "golden", d.name, f.Name+".sql")
			if *update {
				if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
					t.Fatal(err)
				}
				continue
			}
			golden, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("%v (run go test -update)", err)
			}
			if string(golden) != b.String() {
				t.Errorf("%s differs from golden:\n%s", path, b.String())
			}
		}
	}
}
