CREATE TABLE IF NOT EXISTS "roles" (
  "id" INTEGER NOT NULL,
  "name" VARCHAR(50) NOT NULL UNIQUE,
  PRIMARY KEY ("id")
);
CREATE TABLE "users" (
  "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "email" VARCHAR(255) NOT NULL,
  "role_id" INTEGER,
  "active" BOOLEAN NOT NULL DEFAULT TRUE,
  "balance" NUMERIC(10,2) DEFAULT 0,
  "settings" JSONB,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_users_email" UNIQUE ("email"),
  CONSTRAINT "fk_users_role" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE SET NULL,
  CONSTRAINT "chk_users_email" CHECK (email <> '')
);
CREATE INDEX "idx_users_role" ON "users" ("role_id");
